---
- name: Download git repos
  git:
    repo: "{{ item.src }}"
    dest: "{{ item.dest }}"
    version: "{{ item.version }}"
    force: "{{ item.force |default(True) }}"
    verify_commit: "{{ item.verify_commit | default(False) }}"
  with_items: "{{ additional_nrpe_checks }}"
  when: item.type == 'git'

- name: Default nrpe command argument when nagios_dont_blame is true
  set_fact:
    default_argument: "$ARG1$"
  when: nagios_dont_blame == true
- name: Default nrpe command argument when nagios_dont_blame is false
  set_fact:
    default_argument: ""
  when: nagios_dont_blame == false

- name: Create check file
  set_fact:
     nrpe_checks: "{{ nrpe_checks |default([]) + [ {
       'command': item[1].command |default( item[1].script_name ),
       'path': item[0].script_path + item[1].script_name |default( item[1].command ),
       'arguments': item[1].arguments |default( default_argument )
     }] }}"
  with_subelements:
     - "{{ additional_nrpe_checks }}"
     - commands
