---
- name: Download git repos
  git:
    repo: "{{ item.src }}"
    dest: "{{ item.dest }}"
    version: "{{ item.version }}"
    force: "{{ item.force |default(True) }}"
    verify_commit: "{{ item.verify_commit | default(False) }}"
  with_items: "{{ additional_nrpe_checks }}"
  when: item.type == 'git'

- name: set SELinux contexts for checks
  sefcontext:
    target: "{{ item.dest }}"
    setype: "{{ item.setype }}"
    state: "{{ item.state }}"
  with_items: "{{ additional_nrpe_checks }}"
  when: item.setype is defined
  nofity: SELinux context changed

- name: Genereate facts for additional nrpe checks
  set_fact:
     nrpe_checks: "{{ nrpe_checks |default([]) + [ {
       'command': item[1].command |default( item[1].script_name ),
       'path': item[0].script_path + item[1].script_name |default( item[1].command ),
       'arguments': item[1].arguments |default( nagios_default_argument )
     }] }}"
  with_subelements:
     - "{{ additional_nrpe_checks }}"
     - commands
