---
# tasks file for ansible-role-nrpe
#
- name: Install nrpe package
  yum: state=present name=nrpe
  notify:
    - "restart nrpe"

- name: Install extra nrpe packages
  yum: state=present name={{ item }}
  with_items: nrpe_extra_rpms
  notify:
    - "restart nrpe"

- name: Template in override config file (to set allowed_hosts)
  template: src=override.cfg.j2 dest={{ nagios_cfg_file }} mode=0644
            owner={{ nrpe_user }} group={{ nrpe_group }}
  notify:
    - "restart nrpe"

- name: Template in custom checks config file 
  template: src=check_nagios.cfg.j2 
            dest={{ nagios_include_dir }}/{{ nagios_custom_checks_file }} 
            mode=0640
            owner={{ nrpe_user }} group={{ nrpe_group }}
  with_items: nagios_plugins
  notify:
    - "restart nrpe"
