---
# tasks file for ansible-role-nrpe

# GPG check is disabled because opsview are not signing their packages.
- name: Install opsview-agent package
  yum: state=present name=opsview-agent disable_gpg_check=yes
  notify:
    - "restart opsview-agent"

- name: Remove all hardcoded command settings from default nrpe.cfg
  lineinfile:
    state: absent
    regexp: '^command\['
    path: '/usr/local/nagios/etc/nrpe.cfg'
  notify:
    - "restart opsview-agent"
  when: remove_hardcoded_checks|default(false)|bool

- name: Template in override config file (to set allowed_hosts)
  template: src=override.cfg.j2 dest={{ opsview_cfg_file }} mode=0644
            owner={{ nrpe_user }} group={{ nrpe_group }}
  notify:
    - "restart opsview-agent"

- name: Template in custom checks config file for opsview
  template: src=check_opsview.cfg.j2
            dest={{ opsview_include_dir }}/{{ nagios_custom_checks_file }}
            mode=0644
            owner={{ nrpe_user }} group={{ nrpe_group }}
  with_items: "{{ opsview_plugins }}"
  tags: update_opsview_cfg
  notify:
    - "restart opsview-agent"

- name: Make sure opsview-agent is started and enabled
  service: name=opsview-agent state=started enabled=yes
